{
 "title": "Clickhouse",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "慢日志数量 1s",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    query_kind, \n    count(*) AS slow_queries \nFROM system.query_log \nWHERE event_time > now() - INTERVAL 1 HOUR \nAND query_duration_ms > 1000 \nGROUP BY query_kind \nORDER BY slow_queries DESC;\n"
    }
   ]
  },
  {
   "title": "慢日志",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    normalized_query_hash, \n    any(query) AS sample_query,  -- 选取示例 SQL\n    count(*) AS slow_count, \n    avg(query_duration_ms) AS avg_duration, \n    max(query_duration_ms) AS max_duration \nFROM system.query_log \nWHERE event_time > now() - INTERVAL 1 HOUR \nAND query_duration_ms > 1000 \nGROUP BY normalized_query_hash \nORDER BY slow_count DESC \nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "当前活跃查询",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    query, \n    query_duration_ms, \n    read_rows, \n    written_rows, \n    memory_usage \nFROM system.query_log \nWHERE event_time > now() - INTERVAL 10 MINUTE \nORDER BY event_time DESC \nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "每分钟查询次数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfMinute(event_time) AS minute, \n    count(*) AS query_count \nFROM system.query_log \nWHERE event_time > now() - INTERVAL 1 HOUR \nGROUP BY minute \nORDER BY minute;\n"
    }
   ]
  },
  {
   "title": "每分钟写入次数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "rawSql": "SELECT \n    toStartOfMinute(event_time) AS minute, \n    sum(rows) AS total_rows_written \nFROM system.part_log \nWHERE event_time > now() - INTERVAL 1 HOUR \nGROUP BY minute \nORDER BY minute;\n\n"
    }
   ]
  }
 ]
}